---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - chart: kube-state-metrics
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 5.10.1
      helm:
        releaseName: kube-state-metrics
        valueFiles:
        - $values/release/values.yaml
    - repoURL: https://github.com/IanHewlett/demo-platform-service-kube-state-metrics.git
      targetRevision: main
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
